name: Locust Test

on:
  push:
    branches: [ "main", "Develop", "Saving-locust-reports"]

  pull_request:
    branches: [ "main", "Develop", "Saving-locust-reports"]

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      # This will only run if the requirements file exists
      run: |
         cd Source
         python -m pip install --upgrade pip
         pip install charset-normalizer
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Django Server
      # Build the Django Sever to run tests on
      run: |
       cd Source
       python manage.py runserver &

    - name: Run & Generate Locust Test
      # Run the test with no GUI and 100 users for 60 seconds then produce a csv report
      run: |
        cd Source
        locust --headless -u 100 --run-time 60 --host http://127.0.0.1:8000/ --csv locust

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git pull origin ${{ github.head_ref }}
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi

      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}