name: Locust Test

on:
  push:
    branches: [ "main", "Develop", "Saving-locust-reports"]

  pull_request:
    branches: [ "main", "Develop", "Saving-locust-reports"]

jobs:
  locust:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    -  uses: actions/checkout@v4
       with:
         ref: ${{ github.head_ref }}

    - name: install
      # This will only run if the requirements file exists
      run: |
         cd Source
         python -m pip install --upgrade pip
         pip install charset-normalizer
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Django Server
      # Build the Django Sever to run tests on
      run: |
       cd Source
       python manage.py runserver &

    - name: Run & Generate Locust Test
      # Run the test with no GUI and 100 users for 60 seconds then produce a csv report
      run: |
        cd Source
        locust --headless -u 100 --run-time 60 --host http://127.0.0.1:8000/ --csv locust

      # Other steps that change files in the repository
      # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5