name: Performance Testing

on:
  push:
    branches:
      - main
jobs:
  performance-testing:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    - name: Run Locust performance test
      run: |
        locust -f path/to/your/locustfile.py --headless -u 10 -r 2 --run-time 1m

    - name: Upload Locust reports as artifact
      uses: actions/upload-artifact@v2
      with:
        name: locust-reports
        path: locust-reports
