# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Locust Test

on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main", "Development" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      #Install locust from dependencies that's included in requirements.txt 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Django Server
    #Run server and put it the background.
      run: | 
        cd Source
        python manage.py runserver &

    - name: Run Locust
      #Run locust test file to concurrent users
      run: |
        cd Source
        locust -f testLocust.py
      
